version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command: 
      - --retry
      #- --debug
      - --docker.domain=${DOMAIN:-docker.localhost}
      - --api.dashboard
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-docker.localhost}"
      - "traefik.port=8080"
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: traefik