version: '3'

services:
  traefik:
    image: traefik:1.7-alpine
    container_name: traefik
    restart: always
    command: 
      - --retry
      #- --debug
      - --docker.domain=${DOMAIN:-docker.localhost}
      - --api.dashboard
      - --defaultentrypoints=http,https
      - "--entryPoints=Name:http Address::80"
      - "--entryPoints=Name:https Address::443 TLS"
      - --acme.email=${EMAIL}
      - --acme.storage=/etc/acme/acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpchallenge.entrypoint=http
    labels:
      - "traefik.frontend.rule=Host:traefik.${DOMAIN:-docker.localhost}"
      - "traefik.port=8080"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/acme
      #- ./traefik.toml:/traefik.toml

networks:
  default:
    external:
      name: traefik
volumes: 
  acme: